spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${SPRING_DATASOURCE_URL_ENDPOINT}:${SPRING_DATASOURCE_URL_PORT}/${SPRING_DATASOURCE_URL_DB_NAME}?useUnicode=true&characterEncoding=UTF-8&rewriteBatchedStatements=TRUE
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      enabled: true
application:
  jwt:
    secret:
      key: ${APPLICATION_JWT_SECRET_KEY}
  expiration:
    time: ${APPLICATION_JWT_EXPIRATION_TIME}
    refresh:
      time: ${APPLICATION_JWT_EXPIRATION_REFRESH_TIME}
  enabled:
    job: ${APPLICATION_ENABLED_JOB}
    cors:
      allowed:
        origins:${APPLICATION_CORS_ALLOWED_ORIGINS}
server:
  port: ${SERVER_PORT}
swagger:
  config:
    password-flow: true

